#!/usr/bin/env bash
# Update package lists and install Nginx
apt-get update
apt-get install -y nginx
sed -i 's/listen 80 default_server;/listen 0.0.0.0:80 default_server;/g' /etc/nginx/sites-available/default
service nginx start
service nginx restart